### ISSUE TITLE
SassError: Undefined variable: "$utilities-text-colors"

### ISSUE THREAD

**Issue by nimdeveloper** [fncolon/mazer-nuxt#106]
I cloned the project, and run `npm install` (without any changes anywhere), then `npm run dev` and these are the errors I get

![image](https://user-images.githubusercontent.com/34796399/136717431-6f3ad4da-f0ec-4783-a298-0fc03a5174a4.png)

also, it is showing this warning: ``` WARN  sass-loader@12.1.0 is installed but ^10.1.1 is expected ```.
based on this question: https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function, I changed the version of sass-loader to ^10.1.1, but now I get these errors:

![image](https://user-images.githubusercontent.com/34796399/136717795-d2d59a74-9a64-4a51-b972-12812e2f2ae2.png)

You're using bootstrap 5.1.2, but the variables are not synced with bootstrap https://github.com/twbs/bootstrap/blob/v5.1.2/scss/_variables.scss
Is there something that I'm doing wrong?

**Comment by fncolon** [comment]
Sorry for so long inactive! Currently I'm working on this issue.

**Comment by zuramai** [comment]
Fixed #128

**Comment by fncolon** [comment]
Release on https://github.com/fncolon/mazer-nuxt/releases/tag/1.0.1
